/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ExampleImagesRouteImport } from './routes/example-images'
import { Route as DeepReportRouteImport } from './routes/deep-report'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AwarenessRouteImport } from './routes/awareness'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScannerVoiceRouteImport } from './routes/scanner.voice'
import { Route as ScannerUrlRouteImport } from './routes/scanner.url'
import { Route as ScannerTextRouteImport } from './routes/scanner.text'
import { Route as ScannerEmailRouteImport } from './routes/scanner.email'
import { Route as ApiChatRouteImport } from './routes/api.chat'

const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleImagesRoute = ExampleImagesRouteImport.update({
  id: '/example-images',
  path: '/example-images',
  getParentRoute: () => rootRouteImport,
} as any)
const DeepReportRoute = DeepReportRouteImport.update({
  id: '/deep-report',
  path: '/deep-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AwarenessRoute = AwarenessRouteImport.update({
  id: '/awareness',
  path: '/awareness',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerVoiceRoute = ScannerVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => ScannerRoute,
} as any)
const ScannerUrlRoute = ScannerUrlRouteImport.update({
  id: '/url',
  path: '/url',
  getParentRoute: () => ScannerRoute,
} as any)
const ScannerTextRoute = ScannerTextRouteImport.update({
  id: '/text',
  path: '/text',
  getParentRoute: () => ScannerRoute,
} as any)
const ScannerEmailRoute = ScannerEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => ScannerRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/awareness': typeof AwarenessRoute
  '/chat': typeof ChatRoute
  '/deep-report': typeof DeepReportRoute
  '/example-images': typeof ExampleImagesRoute
  '/history': typeof HistoryRoute
  '/scanner': typeof ScannerRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/scanner/email': typeof ScannerEmailRoute
  '/scanner/text': typeof ScannerTextRoute
  '/scanner/url': typeof ScannerUrlRoute
  '/scanner/voice': typeof ScannerVoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/awareness': typeof AwarenessRoute
  '/chat': typeof ChatRoute
  '/deep-report': typeof DeepReportRoute
  '/example-images': typeof ExampleImagesRoute
  '/history': typeof HistoryRoute
  '/scanner': typeof ScannerRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/scanner/email': typeof ScannerEmailRoute
  '/scanner/text': typeof ScannerTextRoute
  '/scanner/url': typeof ScannerUrlRoute
  '/scanner/voice': typeof ScannerVoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/awareness': typeof AwarenessRoute
  '/chat': typeof ChatRoute
  '/deep-report': typeof DeepReportRoute
  '/example-images': typeof ExampleImagesRoute
  '/history': typeof HistoryRoute
  '/scanner': typeof ScannerRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/scanner/email': typeof ScannerEmailRoute
  '/scanner/text': typeof ScannerTextRoute
  '/scanner/url': typeof ScannerUrlRoute
  '/scanner/voice': typeof ScannerVoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/awareness'
    | '/chat'
    | '/deep-report'
    | '/example-images'
    | '/history'
    | '/scanner'
    | '/api/chat'
    | '/scanner/email'
    | '/scanner/text'
    | '/scanner/url'
    | '/scanner/voice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/awareness'
    | '/chat'
    | '/deep-report'
    | '/example-images'
    | '/history'
    | '/scanner'
    | '/api/chat'
    | '/scanner/email'
    | '/scanner/text'
    | '/scanner/url'
    | '/scanner/voice'
  id:
    | '__root__'
    | '/'
    | '/awareness'
    | '/chat'
    | '/deep-report'
    | '/example-images'
    | '/history'
    | '/scanner'
    | '/api/chat'
    | '/scanner/email'
    | '/scanner/text'
    | '/scanner/url'
    | '/scanner/voice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AwarenessRoute: typeof AwarenessRoute
  ChatRoute: typeof ChatRoute
  DeepReportRoute: typeof DeepReportRoute
  ExampleImagesRoute: typeof ExampleImagesRoute
  HistoryRoute: typeof HistoryRoute
  ScannerRoute: typeof ScannerRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example-images': {
      id: '/example-images'
      path: '/example-images'
      fullPath: '/example-images'
      preLoaderRoute: typeof ExampleImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deep-report': {
      id: '/deep-report'
      path: '/deep-report'
      fullPath: '/deep-report'
      preLoaderRoute: typeof DeepReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awareness': {
      id: '/awareness'
      path: '/awareness'
      fullPath: '/awareness'
      preLoaderRoute: typeof AwarenessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner/voice': {
      id: '/scanner/voice'
      path: '/voice'
      fullPath: '/scanner/voice'
      preLoaderRoute: typeof ScannerVoiceRouteImport
      parentRoute: typeof ScannerRoute
    }
    '/scanner/url': {
      id: '/scanner/url'
      path: '/url'
      fullPath: '/scanner/url'
      preLoaderRoute: typeof ScannerUrlRouteImport
      parentRoute: typeof ScannerRoute
    }
    '/scanner/text': {
      id: '/scanner/text'
      path: '/text'
      fullPath: '/scanner/text'
      preLoaderRoute: typeof ScannerTextRouteImport
      parentRoute: typeof ScannerRoute
    }
    '/scanner/email': {
      id: '/scanner/email'
      path: '/email'
      fullPath: '/scanner/email'
      preLoaderRoute: typeof ScannerEmailRouteImport
      parentRoute: typeof ScannerRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ScannerRouteChildren {
  ScannerEmailRoute: typeof ScannerEmailRoute
  ScannerTextRoute: typeof ScannerTextRoute
  ScannerUrlRoute: typeof ScannerUrlRoute
  ScannerVoiceRoute: typeof ScannerVoiceRoute
}

const ScannerRouteChildren: ScannerRouteChildren = {
  ScannerEmailRoute: ScannerEmailRoute,
  ScannerTextRoute: ScannerTextRoute,
  ScannerUrlRoute: ScannerUrlRoute,
  ScannerVoiceRoute: ScannerVoiceRoute,
}

const ScannerRouteWithChildren =
  ScannerRoute._addFileChildren(ScannerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AwarenessRoute: AwarenessRoute,
  ChatRoute: ChatRoute,
  DeepReportRoute: DeepReportRoute,
  ExampleImagesRoute: ExampleImagesRoute,
  HistoryRoute: HistoryRoute,
  ScannerRoute: ScannerRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
